name: recipe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/auth/
    - assets/icons/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
